config/routes.rb
Rails.application.routes.draw do

  get  '/login',  to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  get  '/logout', to: 'sessions#destroy'

  # Help to understand routing
  # http://guides.rubyonrails.org/routing.html

  namespace :admin do
    get '/', to: 'dashboard#index'

    resources :semesters, path: 'semestres'
    resources :laboratories, path: 'laboratorios'
    resources :classrooms, path: 'turmas'
    resources :schoolrooms, path: 'salas'
    resources :authorizations, path: 'autorizacoes'

    resources :campus do
      get 'importar', to: 'campus#import', on: :collection
      resources :campus_schedules, only: [:index, :new, :create, :destroy], path: 'horarios'
    end

    resource :courses do
      post 'importar', to: 'courses#import'
    end

    resources :course_subject, only: [:index], path: 'disciplinas' do
        post 'importar', to: 'course_subject#import', on: :collection
    end

    resources :teacher, only: [:index], path: 'professores' do
        post 'importar', to: 'teacher#import', on: :collection
    end
  end
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  belongs_to :course
  belongs_to :course_subject
  belongs_to :teacher
end

app/controllers/admin/classrooms_controller.rb
class Admin::ClassroomsController < Admin::AdminController
  before_action :set_classroom, only: [:show, :edit, :update, :destroy]

  def index
    @classrooms = Classroom.all
  end

  def show
  end

  def new
    @classroom = Classroom.new
  end

  def edit
  end

  def create
    @classroom = Classroom.new(classroom_params)

    respond_to do |format|
      if @classroom.save
        format.html { redirect_to admin_classroom_path(@classroom), notice: 'Turma criada com sucesso' }
        format.json { render :show, status: :created, location: @classroom }
      else
        format.html { render :new }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @classroom.update(classroom_params)
        format.html { redirect_to admin_classroom_path(@classroom), notice: 'Turma criada com sucesso' }
        format.json { render :show, status: :ok, location: @classroom }
      else
        format.html { render :edit }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @classroom.destroy
    respond_to do |format|
      format.html { redirect_to admin_classrooms_url, notice: 'Turma excluída com sucesso' }
      format.json { head :no_content }
    end
  end

  private
    def set_classroom
      @classroom = Classroom.find(params[:id])
    end

    def classroom_params
      params.require(:classroom).permit(:name, :code, :course_id, :course_subject_id, :teacher_id, :semester, :observations)
    end
end

app/views/admin/classrooms/_form.html.erb
<style>
  label {
    display: block;
    margin-bottom: 5px;
  }
</style>
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="row">
          <div class="col-md-8">
            <svg class="glyph stroked notepad "><use xlink:href="#stroked-notepad"/></svg>
            <%- if not classroom.nil? and classroom.name and not classroom.name.empty?  %>
              <%= classroom.name %>
            <% else %>
              Nova turma
            <% end %>
          </div>
        </div>
      </div>
      <div class="panel-body">
        <%= form_for([:admin, classroom]) do |form| %>
        <% if classroom.errors.any? %>
          <ul class="alert alert-danger">
            <% classroom.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>

        <div class="form-group">
          <%= form.label :name, "Nome" %>
          <%= form.text_field :name, id: :classroom_name, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :code, "Identificador" %>
          <%= form.text_field :code, id: :classroom_code, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :course_id, "Curso" %>
          <%= form.select("course_id", options_from_collection_for_select(Course.all, 'id', 'description'), {}, class: "selectpicker", data: {'live-search' => 'true', width: "auto"}) %>
        </div>

        <div class="form-group">
          <%= form.label :course_subject_id, "Disciplina" %>
          <%= form.select("course_subject_id", options_from_collection_for_select(CourseSubject.all, 'id', 'description'), {}, class: "selectpicker", data: {'live-search' => 'true', width: "auto"}) %>
        </div>

        <div class="form-group">
          <%= form.label :teacher_id, "Professor" %>
          <%= form.select("teacher_id", options_from_collection_for_select(Teacher.all, 'registration', 'name'), {}, class: "selectpicker", data: {'live-search' => 'true', width: "auto"}) %>
        </div>

        <div class="form-group">
          <%= form.label :semester, "Período" %>
          <%= form.number_field :semester, id: :classroom_semester, class: "form-control"  %>
        </div>

        <div class="form-group">
          <%= form.submit 'Save', class: 'btn btn-success pull-right' %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
$('#xclassroom_course_id').selectpicker({
  size: 100
});
</script>

app/views/admin/classrooms/edit.html.erb
<%= render 'form', classroom: @classroom %>

<%= link_to 'Show', admin_classroom_path(@classroom) %> |
<%= link_to 'Back', admin_classrooms_path %>

app/views/admin/classrooms/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="row">
          <div class="col-md-8">
            <svg class="glyph stroked notepad "><use xlink:href="#stroked-notepad"/></svg> Turmas
          </div>
          <div class="col-md-4">
            <%= link_to 'Nova turma', new_admin_classroom_path, class: "btn btn-success pull-right" %>
          </div>
        </div>
      </div>
      <div class="panel-body">

        <table data-toggle="table" id="table-import" data-search="true" data-pagination="true">
          <thead>
              <th>Identificador</th>
              <th>Nome</th>
              <th>Curso</th>
              <th>Disciplina</th>
              <th>Professor</th>
              <th>Período</th>
              <th> </th>
              <th> </th>
          </thead>

          <tbody>
            <% @classrooms.each do |admin_classroom| %>
            <tr>
              <td><%= admin_classroom.code %></td>
              <td><%= link_to(admin_classroom.name, admin_classroom_path(admin_classroom)) %></td>
              <td><%= admin_classroom.course.description %></td>
              <td><%= admin_classroom.course_subject.description %></td>
              <td><%= admin_classroom.teacher.name %></td>
              <td><%= admin_classroom.semester %></td>
              <td><%= link_to 'Edit', edit_admin_classroom_path(admin_classroom), class: "btn btn-default" %></td>
              <td><%= link_to 'Delete', admin_classroom_path(admin_classroom), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
            </tr>
            <% end %>
          </tbody>
        </table>

      </div>
    </div>
  </div>
</div>

app/views/admin/classrooms/new.html.erb
<div class="row">
  <div class="col-lg-12">
  </div>
</div>

<%= render 'form', classroom: @classroom %>

app/views/admin/classrooms/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="row">
          <div class="col-md-8">
            <svg class="glyph stroked notepad "><use xlink:href="#stroked-notepad"/></svg> <%= @classroom.name %>
          </div>
          <div class="col-md-4">
            <%= link_to t('Edit'), edit_admin_classroom_path(@classroom), class: "btn btn-success pull-right" %>
          </div>
        </div>
      </div>
      <div class="panel-body">
      <p id="notice"><%= notice %></p>

        <p>
          <strong>Nome: </strong>
          <%= @classroom.name %>
        </p>

        <p>
          <strong>Identificador:</strong>
          <%= @classroom.code %>
        </p>

        <p>
          <strong>Curso:</strong>
          <%= @classroom.course.description %>
        </p>

        <p>
          <strong>Disciplina:</strong>
          <%= @classroom.course_subject.description %>
        </p>

        <p>
          <strong>Professor:</strong>
          <%= @classroom.teacher.name %>
        </p>

        <p>
          <strong>Período:</strong>
          <%= @classroom.semester %>
        </p>

        <p>
          <strong>Observações:</strong>
          <%= @classroom.observations %>
        </p>

        <%= link_to t('Back'), admin_classrooms_path, class: "btn btn-default" %>
      </div>
    </div>
  </div>
</div>