config/routes.rb
Rails.application.routes.draw do

  get  '/login',  to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  get  '/logout', to: 'sessions#destroy'

  # Help to understand routing
  # http://guides.rubyonrails.org/routing.html

  namespace :admin do
    get '/', to: 'dashboard#index'

    resources :semesters, path: 'semestres'
    resources :laboratories, path: 'laboratorios'
    resources :classrooms, path: 'turmas'
    resources :schoolrooms, path: 'salas'
    resources :authorizations, path: 'autorizacoes'

    resources :campus do
      get 'importar', to: 'campus#import', on: :collection
      resources :campus_schedules, only: [:index, :new, :create, :destroy], path: 'horarios'
    end

    resource :courses do
      post 'importar', to: 'courses#import'
    end

    resources :course_subject, only: [:index], path: 'disciplinas' do
        post 'importar', to: 'course_subject#import', on: :collection
    end

    resources :teacher, only: [:index], path: 'professores' do
        post 'importar', to: 'teacher#import', on: :collection
    end
  end
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authorization.rb
class Authorization < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/models/campus.rb
class Campus < ApplicationRecord
  validates :description, :sigla, presence: true

  has_many :courses
end

app/models/campus_schedule.rb
class CampusSchedule < ApplicationRecord
  enum shift: {morning: 1, afternoon: 2, nightly: 3}
  belongs_to :campus
  validates :start, :end, :shift, presence: true
  validates_uniqueness_of :campus_id, scope: [:start, :end]
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  belongs_to :course
  belongs_to :course_subject
  belongs_to :teacher
end

app/models/course.rb
class Course < ApplicationRecord
  validates :name, :description, :code, presence: true
  belongs_to :campus
  has_many :classrooms
end

app/models/course_subject.rb
class CourseSubject < ApplicationRecord
  belongs_to :course
  validates :initials, :description, :semester, presence: true
  has_many :classrooms
end

app/models/laboratory.rb
class Laboratory < ApplicationRecord
  validates :maximum_capacity, :amount_resources, :name, :initials, presence: true
  validates :maximum_capacity, :numericality => { :greater_than_or_equal_to => 0 }
  validates :amount_resources, :numericality => { :greater_than_or_equal_to => 0 }
  validate :exist_other_with_this_initials
  validate :exist_other_with_this_name

  def exist_other_with_this_initials
    @laboratories = Laboratory.all
    unless initials.nil?
    @laboratories.each { |l|
      unless l.id == id
        errors.add(:initials, 'Outro laboratório já possui sigla informada') if l.initials.casecmp(initials) == 0
      end
    }
    end
  end

  def exist_other_with_this_name
    @laboratories = Laboratory.all
    unless name.nil?
    @laboratories.each { |l|
      unless l.id == id
        errors.add(:initials, 'Outro laboratório já possui nome informada') if l.name.casecmp(name) == 0
      end
    }
    end
  end
end

app/models/schoolroom.rb
class Schoolroom < ApplicationRecord
  validates :maximum_capacity, :amount_resources, :name, :initials, presence: true
  validates :maximum_capacity, :numericality => { :greater_than_or_equal_to => 0 }
  validates :amount_resources, :numericality => { :greater_than_or_equal_to => 0 }
  validate :exist_other_with_this_initials
  validate :exist_other_with_this_name

  def exist_other_with_this_initials
    @schoolrooms = Schoolroom.all
    unless initials.nil?
    @schoolrooms.each { |s|
      unless s.id == id
        errors.add(:initials, 'Outra sala já possui sigla informada') if s.initials.casecmp(initials) == 0
      end
    }
    end
  end

  def exist_other_with_this_name
    @schoolrooms = Schoolroom.all
    unless name.nil?
    @schoolrooms.each { |s|
      unless s.id == id
        errors.add(:initials, 'Outra sala já possui nome informado') if s.name.casecmp(name) == 0
      end
    }
    end
  end
end

app/models/semester.rb
class Semester < ApplicationRecord
  validates :year, :semester, presence: true, on: :create
	validates :year, uniqueness: { scope: :semester,
    message: "should not have same year and semester togeter" }
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  validates :registration, :name, :mail, presence: true
  has_many :classrooms
end

app/models/user.rb
class User < ApplicationRecord
  validates :registration, presence: true, admin: false
  
  def admin?
    admin
  end
end

app/controllers/admin/semesters_controller.rb
class Admin::SemestersController < Admin::AdminController
  include Admin::ImportHelper

  def index
    @semesters = Semester.all
  end

  def new
    @semester = Semester.new
  end

  def create
    @semester = Semester.new semester_params
    @semester.id = (@semester.year + @semester.semester).to_i

    if @semester.valid?
      @semester.save
      redirect_to admin_semesters_path
    else
      flash[:danger] = @semester.errors.full_messages.to_sentence
      render 'new'
    end
  end

  def show
    @semester = Semester.find(params[:id])
  end

  def edit
    @semester = Semester.find(params[:id])
  end

  def update
    @semester = Semester.find(params[:id])
    if @semester.update(semester_params)
      redirect_to admin_semesters_path
    else
      flash[:danger] = @semester.errors.full_messages.to_sentence
      render 'edit'
    end
  end

  def destroy
    @semester = Semester.find(params[:id])
    @semester.destroy

    redirect_to admin_semesters_path
  end

  private
    def semester_params
      params.require(:semester).permit(:year, :semester, :start_date, :end_date)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include Admin::ImportHelper
  
  def new
    if logged_in?
      redirect_to "/admin"
    end
  end

  def create
    reg = params[:session][:matricula]
    pass = params[:session][:password]
    token = auth reg, pass
    
    unless token.nil?
      user = User.find_by(registration: reg)
      if user.nil?
        user = User.new(registration: reg)
        user.save
      end
      
      autho = Authorization.find_by(user: user)
      if not autho.nil? or user.admin?
        log_in user
        redirect_to "/admin"
      else
        flash.now[:notice] = "Permissão negada"
        render 'new'
      end
    else
      flash.now[:notice] = "Dados inválidos"
      render 'new'
    end
  end
  
  def auth(registation, password)
    dados = {"user": registation, "password": password}
    response = request_suap_api({url: 'https://suap.ifpb.edu.br/ldap_backend/auth/', data: dados})

    if response.nil? or response.empty?
      return nil
    end
    
    return response['token']
  end

  def destroy
    log_out
    redirect_to "/login"
  end
end

app/helpers/admin/campus_helper.rb
module Admin::CampusHelper
end

app/helpers/admin/import_helper.rb
module Admin::ImportHelper

  def request_suap_api(params={})

    if params[:url].nil?
      return nil
    end

    if ENV['SUAP_TOKEN'].nil?
      raise 'Please configure SUAP TOKEN'
    end

    header = {'Authorization': "Token #{ENV['SUAP_TOKEN']}"}
    uri = URI.parse(params[:url])
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true

    request = Net::HTTP::Post.new(uri.request_uri, header)

    if not params[:data].nil?
      request.body = ""
      params[:data].each do |key, value|
        request.body += "#{key}=#{value}&"
      end
    end

    response = http.request(request)

    unless response.body.length == 0
      JSON.parse(response.body)
    end
  end
end

app/helpers/admin/schoolrooms_helper.rb
module Admin::SchoolroomsHelper
end

app/helpers/admin/semesters_helper.rb
module Admin::SemestersHelper
end

app/helpers/admin/teacher_helper.rb
module Admin::TeacherHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  def user_is_admin?
    current_user.admin?
  end
end

app/views/admin/semesters/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Editar Semestre</h1>
  </div>
</div><!--/.row-->

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="row">
          <div class="col-md-8">
            Semestre <%= @semester.id %>
          </div>
        </div>
      </div>
      <%= form_for @semester, url: admin_semester_path(@semester), html: { method: :patch } do |f| %>
        <div class="panel-body" style="text-align: center">
         
					<div class="row">
            <div class="col-md-6">
              <%= f.select :year, (Time.now.year - 5)..Time.now.year %>
            </div>
            <div class="col-md-6">
              <%= f.select :semester, 1..2 %>
            </div>
          </div>
					
          <div class="row">
            <div class="col-md-12">
              <%= f.submit 'Salvar', class: 'btn btn-success' %>
            </div>
          </div>
        <% end %>
      </div><!-- panel-body -->
    </div><!-- panel panel-default -->
  </div>
</div>

app/views/admin/semesters/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Semestres</h1>
  </div>
</div><!--/.row-->

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="row">
          <div class="col-md-8">
            <svg class="glyph stroked calendar"><use xlink:href="#stroked-calendar"/></svg> Semestres Letivos
          </div>
          <div class="col-md-4">
            <%= link_to('Novo Semestre', new_admin_semester_path, class: "btn btn-success pull-right")%>
          </div>
        </div>
      </div>
      <div class="panel-body">
        <table data-toggle="table" id="table-import" data-search="true" data-pagination="true">
          <thead>
            <th>Id</th>
            
            <th colspan="3" style="text-align:center">Operações</th>
          </thead>
          <tbody>
            <% @semesters.each do |semester| %>
            <tr>
              <td> <%= semester.id %></td>

              <td style="text-align:center">
                <%= link_to admin_semester_path(semester), class: "label label-info" do %>
                <span>Detalhes</span>
                <% end %>
              </td>
              <td style="text-align:center">
                <%= link_to edit_admin_semester_path(semester), class: "label label-primary" do %>
                <span>Editar</span>
                <% end %>
              </td>
              <td style="text-align:center">
                <%= link_to admin_semester_path(semester),
                method: :delete,
                data: { confirm: 'Tem certeza que quer apagar
                  semestre letivo?' },
                  class: "label label-danger" do %>
                  <span>Excluir</span>
                  <% end %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

app/views/admin/semesters/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="form-inline">
        <div class="panel-heading"><svg class="glyph stroked calendar"><use xlink:href="#stroked-calendar"></use></svg> Novo semestre</div>
        <div class="panel-body">
          <div class="col-md-12">
            <%= form_for :semester, class: 'form-control', url: admin_semesters_path do |f| %>
            <div class="row">
              <div class="col-md-3"></div>
              <div class="col-md-3">
                <div class="form-group">
                  <%= f.label :year, "Ano"%>
                  <%= f.select :year, (Time.now.year - 5)..Time.now.year , class:"form-control select-semester" %>
                </div>
              </div>
              <div class="col-md-3">
                <div class="form-group">
                  <%= f.label :semester, "Semestre"%>
                  <%= f.select :semester, 1..2 , class:"form-control"%>
                </div>
              </div>
              <div class="col-md-3"></div>
            </div>
            <div class="row">
              <div class="col-md-5">
              </div>
              <div class="col-md-5">
                <%= f.submit 'Salvar', class: 'btn btn-success button-semester' %>
              </div>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/semesters/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Detalhes do Semestre</h1>
  </div>
</div><!--/.row-->

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-body" style="text-align: center">
        <div class="row">
          <div class="col-md-4">
            <b>Periodo</b>
          </div>

        </div>

        <div class="row">
          <div class="col-md-4">
            <%= @semester.id %>
          </div>
         
        </div>
      </div> <!-- panel-body -->
    </div> <!-- panel panel-default -->
  </div>
</div> <!--/.row-->
</table>