config/routes.rb
Rails.application.routes.draw do

  get  '/login',  to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  get  '/logout', to: 'sessions#destroy'

  # Help to understand routing
  # http://guides.rubyonrails.org/routing.html

  namespace :admin do
    get '/', to: 'dashboard#index'

    resources :semesters, path: 'semestres'
    resources :laboratories, path: 'laboratorios'
    resources :classrooms, path: 'turmas'
    resources :schoolrooms, path: 'salas'
    resources :authorizations, path: 'autorizacoes'

    resources :campus do
      get 'importar', to: 'campus#import', on: :collection
      resources :campus_schedules, only: [:index, :new, :create, :destroy], path: 'horarios'
    end

    resource :courses do
      post 'importar', to: 'courses#import'
    end

    resources :course_subject, only: [:index], path: 'disciplinas' do
        post 'importar', to: 'course_subject#import', on: :collection
    end

    resources :teacher, only: [:index], path: 'professores' do
        post 'importar', to: 'teacher#import', on: :collection
    end
  end
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authorization.rb
class Authorization < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/models/campus.rb
class Campus < ApplicationRecord
  validates :description, :sigla, presence: true

  has_many :courses
end

app/models/campus_schedule.rb
class CampusSchedule < ApplicationRecord
  enum shift: {morning: 1, afternoon: 2, nightly: 3}
  belongs_to :campus
  validates :start, :end, :shift, presence: true
  validates_uniqueness_of :campus_id, scope: [:start, :end]
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  belongs_to :course
  belongs_to :course_subject
  belongs_to :teacher
end

app/models/course.rb
class Course < ApplicationRecord
  validates :name, :description, :code, presence: true
  belongs_to :campus
  has_many :classrooms
end

app/models/course_subject.rb
class CourseSubject < ApplicationRecord
  belongs_to :course
  validates :initials, :description, :semester, presence: true
  has_many :classrooms
end

app/models/laboratory.rb
class Laboratory < ApplicationRecord
  validates :maximum_capacity, :amount_resources, :name, :initials, presence: true
  validates :maximum_capacity, :numericality => { :greater_than_or_equal_to => 0 }
  validates :amount_resources, :numericality => { :greater_than_or_equal_to => 0 }
  validate :exist_other_with_this_initials
  validate :exist_other_with_this_name

  def exist_other_with_this_initials
    @laboratories = Laboratory.all
    unless initials.nil?
    @laboratories.each { |l|
      unless l.id == id
        errors.add(:initials, 'Outro laboratório já possui sigla informada') if l.initials.casecmp(initials) == 0
      end
    }
    end
  end

  def exist_other_with_this_name
    @laboratories = Laboratory.all
    unless name.nil?
    @laboratories.each { |l|
      unless l.id == id
        errors.add(:initials, 'Outro laboratório já possui nome informada') if l.name.casecmp(name) == 0
      end
    }
    end
  end
end

app/models/schoolroom.rb
class Schoolroom < ApplicationRecord
  validates :maximum_capacity, :amount_resources, :name, :initials, presence: true
  validates :maximum_capacity, :numericality => { :greater_than_or_equal_to => 0 }
  validates :amount_resources, :numericality => { :greater_than_or_equal_to => 0 }
  validate :exist_other_with_this_initials
  validate :exist_other_with_this_name

  def exist_other_with_this_initials
    @schoolrooms = Schoolroom.all
    unless initials.nil?
    @schoolrooms.each { |s|
      unless s.id == id
        errors.add(:initials, 'Outra sala já possui sigla informada') if s.initials.casecmp(initials) == 0
      end
    }
    end
  end

  def exist_other_with_this_name
    @schoolrooms = Schoolroom.all
    unless name.nil?
    @schoolrooms.each { |s|
      unless s.id == id
        errors.add(:initials, 'Outra sala já possui nome informado') if s.name.casecmp(name) == 0
      end
    }
    end
  end
end

app/models/semester.rb
class Semester < ApplicationRecord
  validates :year, :semester, presence: true, on: :create
	validates :year, uniqueness: { scope: :semester,
    message: "should not have same year and semester togeter" }
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  validates :registration, :name, :mail, presence: true
  has_many :classrooms
end

app/models/user.rb
class User < ApplicationRecord
  validates :registration, presence: true, admin: false
  
  def admin?
    admin
  end
end

app/controllers/admin/laboratories_controller.rb
class Admin::LaboratoriesController < Admin::AdminController
  include Admin::ImportHelper

  def index
    @laboratories = Laboratory.all
  end

  def new
    @laboratory = Laboratory.new
  end

  def create
    @laboratory = Laboratory.new(laboratory_params)

    if @laboratory.save
      redirect_to admin_laboratories_path
    else
      flash[:danger] = @laboratory.errors.full_messages.to_sentence
      render 'new'
    end
  end


  def show
    @laboratory = Laboratory.find(params[:id])
  end
  def edit
    @laboratory = Laboratory.find(params[:id])
  end

  def update
    @laboratory = Laboratory.find(params[:id])

    if @laboratory.update(laboratory_params)
      redirect_to admin_laboratories_path
    else
      flash[:danger] = @laboratory.errors.full_messages.to_sentence
      render 'edit'
    end
  end

  def destroy
    @laboratory = Laboratory.find(params[:id])
    @laboratory.destroy

    redirect_to admin_laboratories_path
  end

  private
    def laboratory_params
      params.require(:laboratory).permit(:maximum_capacity, :amount_resources, :status, :name, :initials)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include Admin::ImportHelper
  
  def new
    if logged_in?
      redirect_to "/admin"
    end
  end

  def create
    reg = params[:session][:matricula]
    pass = params[:session][:password]
    token = auth reg, pass
    
    unless token.nil?
      user = User.find_by(registration: reg)
      if user.nil?
        user = User.new(registration: reg)
        user.save
      end
      
      autho = Authorization.find_by(user: user)
      if not autho.nil? or user.admin?
        log_in user
        redirect_to "/admin"
      else
        flash.now[:notice] = "Permissão negada"
        render 'new'
      end
    else
      flash.now[:notice] = "Dados inválidos"
      render 'new'
    end
  end
  
  def auth(registation, password)
    dados = {"user": registation, "password": password}
    response = request_suap_api({url: 'https://suap.ifpb.edu.br/ldap_backend/auth/', data: dados})

    if response.nil? or response.empty?
      return nil
    end
    
    return response['token']
  end

  def destroy
    log_out
    redirect_to "/login"
  end
end

app/helpers/admin/campus_helper.rb
module Admin::CampusHelper
end

app/helpers/admin/import_helper.rb
module Admin::ImportHelper

  def request_suap_api(params={})

    if params[:url].nil?
      return nil
    end

    if ENV['SUAP_TOKEN'].nil?
      raise 'Please configure SUAP TOKEN'
    end

    header = {'Authorization': "Token #{ENV['SUAP_TOKEN']}"}
    uri = URI.parse(params[:url])
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true

    request = Net::HTTP::Post.new(uri.request_uri, header)

    if not params[:data].nil?
      request.body = ""
      params[:data].each do |key, value|
        request.body += "#{key}=#{value}&"
      end
    end

    response = http.request(request)

    unless response.body.length == 0
      JSON.parse(response.body)
    end
  end
end

app/helpers/admin/laboratories_helper.rb
module Admin::LaboratoriesHelper
end

app/helpers/admin/semesters_helper.rb
module Admin::SemestersHelper
end

app/helpers/admin/teacher_helper.rb
module Admin::TeacherHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  def user_is_admin?
    current_user.admin?
  end
end

app/views/admin/laboratories/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="form-horizontal">
        <div class="panel-heading"><svg class="glyph stroked desktop computer and mobile"><use xlink:href="#stroked-desktop-computer-and-mobile"></use></svg> Editar laboratório</div>
        <div class="panel-body">
          <div class="col-md-12">
            <%= form_for @laboratory, url: admin_laboratory_path(@laboratory), html: { method: :patch } do |f| %>
            <div class="form-group ">
              <%= f.label :name, "Nome", class: "col-sm-2 control-label"%>
              <div class="col-sm-4">
                <%= f.text_field :name , class:"form-control"%>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :initials,"Sigla", class: "col-sm-2 control-label"%>
              <div class="col-sm-2">
                <%= f.text_field :initials, class:"form-control" %>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :maximum_capacity, "Capacidade máxima",class: "col-sm-2 control-label"%>
              <div class="col-sm-2">
                <%= f.number_field :maximum_capacity, class:"form-control" %>
              </div>
            </div>
            <div class="form-group ">
              <%= f.label :amount_resources, "Quantidade de recursos", class: "col-sm-2 control-label" %>
              <div class="col-sm-2">
                <%= f.number_field :amount_resources, class:"form-control"  %>
              </div>
            </div>

            <div class="form-group ">
              <%= f.label :status, class: "col-sm-2 control-label" %>
              <div class="col-sm-2">
                <%= f.select :status, [['Ativo', true], ['Inativo', false]],  class:"form-control"  %>
              </div>

            </div>

            <div class="row">
              <div class="col-md-5">

              </div>
              <div class="col-md-7">
                <%= f.submit 'Salvar', class: 'btn btn-success' %>
              </div>
            </div>

            <% end %>
          </div><!-- panel-body -->
        </div><!-- panel panel-default -->
      </div>
    </div>

app/views/admin/laboratories/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Laboratórios</h1>
  </div>
</div><!--/.row-->

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="row">
          <div class="col-md-8">
            <svg class="glyph stroked calendar"><use xlink:href="#stroked-calendar"/></svg> Laboratórios
          </div>
          <div class="col-md-4">
            <%= link_to('Novo Laboratório', new_admin_laboratory_path, class: "btn btn-success pull-right")%>
          </div>
        </div>
      </div>
      <div class="panel-body">
        <table data-toggle="table" id="table-import" data-search="true" data-pagination="true">
          <thead>
            <th>Id</th>
            <th>Nome</th>
            <th>Sigla</th>
            <th colspan="3" style="text-align:center">Ações</th>
          </thead>

          <tbody>
            <% @laboratories.each do |laboratory| %>
            <tr>
              <td><%= laboratory.id %></td>
              <td><%= laboratory.name %></td>
              <td><%= laboratory.initials %></td>
              <td style="text-align:center">
                <%= link_to admin_laboratory_path(laboratory), class: "label label-info" do %>
                <span>Detalhes</span>
                <% end %>
              </td>
              <td style="text-align:center">
                <%= link_to edit_admin_laboratory_path(laboratory), class: "label label-primary" do %>
                <span>Editar</span>
                <% end %>
              </td>
              <td style="text-align:center">
                <%= link_to admin_laboratory_path(laboratory),
                method: :delete,
                data: { confirm: 'Tem certeza que quer apagar laboratório?' },
                class: "label label-danger" do %>
                <span>Excluir</span>
                <% end %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/laboratories/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="form-horizontal">
        <div class="panel-heading"><svg class="glyph stroked desktop computer and mobile"><use xlink:href="#stroked-desktop-computer-and-mobile"></use></svg> Novo laboratório</div>
        <div class="panel-body">
          <div class="col-md-12">
            <%= form_for :laboratory, url: admin_laboratories_path do |f| %>

            <div class="form-group ">
              <%= f.label :name, "Nome", class: "col-sm-2 control-label"%>
              <div class="col-sm-4">
                <%= f.text_field :name , class:"form-control"%>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :initials,"Sigla", class: "col-sm-2 control-label"%>
              <div class="col-sm-2">
                <%= f.text_field :initials, class:"form-control" %>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :maximum_capacity, "Capacidade máxima",class: "col-sm-2 control-label"%>
              <div class="col-sm-2">
                <%= f.number_field :maximum_capacity, class:"form-control" %>
              </div>
            </div>
            <div class="form-group ">
              <%= f.label :amount_resources, "Quantidade de recursos", class: "col-sm-2 control-label" %>
              <div class="col-sm-2">
                <%= f.number_field :amount_resources, class:"form-control"  %>
              </div>
            </div>

            <div class="form-group ">
              <%= f.label :status, class: "col-sm-2 control-label" %>
              <div class="col-sm-2">
                <%= f.select :status, [['Ativo', true], ['Inativo', false]],  class:"form-control"  %>
              </div>

            </div>

            <div class="row">
              <div class="col-md-5">

              </div>
              <div class="col-md-7">
                <%= f.submit 'Salvar', class: 'btn btn-success' %>
              </div>
            </div>

            <% end %>

          </div>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/admin/laboratories/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default ">
      <div class="form-horizontal">
        <div class="panel-heading"><svg class="glyph stroked desktop computer and mobile"><use xlink:href="#stroked-desktop-computer-and-mobile"></use></svg> Laboratório <%= @laboratory.initials%></div>
          <div class="panel-body">
            <div class="col-md-12">
              <div class="row">
                <div class="col-md-4">
                  <%= label_tag("Nome: ")%>
                  <%= @laboratory.name%>
                </div>
                </div>
                <br />
                <div class="row">
                  <div class="col-md-4">
                    <%= label_tag("Sigla: ")%>
                    <%= @laboratory.initials %>
                  </div>
                </div>
              <br />
              <div class="row ">
                <div class="col-md-4">
                  <%= label_tag("Capacidade máxima: ")%>
                  <%= @laboratory.maximum_capacity %>
                </div>
              </div>
              <br />
              <div class="row">
                <div class="col-md-4">
                  <%= label_tag("Quantidade de recursos: ")%>
                  <%= @laboratory.amount_resources %>
                </div>
              </div>
              <br />
              <div class="row">
                <div class="col-md-3">
                  <%= label_tag("Status: ")%>
                  <% if @laboratory.status? %>
                  <span class="label label-success">Ativo</span>
                  <% else %>
                  <span class="label label-danger">Inativo</span>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>